In [3]:
PRICES = ["NA", 9, 40, 50, 70, 80]

In [6]:
def partition(cake_size):
    """
    partitions of the cake
    :param cake_size: size of the cake
    :return: the best profit possible
    """
    if cake_size <= 0:
        return 0
    best_profit = -1
    for i in range(1, cake_size + 1):
        best_profit = max(best_profit, PRICES[i] + partition(cake_size - i))
    print(f'The best profit for {cake_size} is {best_profit}')
    return best_profit

In [7]:
size = 5
best_profit = partition(size)
print(best_profit)

The best profit for 1 is 9
The best profit for 2 is 40
The best profit for 1 is 9
The best profit for 3 is 50
The best profit for 1 is 9
The best profit for 2 is 40
The best profit for 1 is 9
The best profit for 4 is 80
The best profit for 1 is 9
The best profit for 2 is 40
The best profit for 1 is 9
The best profit for 3 is 50
The best profit for 1 is 9
The best profit for 2 is 40
The best profit for 1 is 9
The best profit for 5 is 90
90


In [18]:
def memoized_partition(cake_size, memo=None):
    if cake_size <= 0:
        return 0
    if cake_size in memo:
        return memo[cake_size]
    else:
        best_profit = -1
        for i in range(1, cake_size + 1):
            best_profit = max(best_profit, PRICES[i] + memoized_partition(cake_size - i, memo))
        print(f'The best profit for {cake_size} is {best_profit}')
        memo[cake_size] = best_profit
        return best_profit

In [20]:
size = 5
best_profit = memoized_partition(size, {})
print(best_profit)

The best profit for 1 is 9
The best profit for 2 is 40
The best profit for 3 is 50
The best profit for 4 is 80
The best profit for 5 is 90
90


In [26]:
def (n):
    if n <= 1:
        return 0
    elif n == 2:
        return 1
    else:
        return (n-1) + (n-2) + (n-3)


In [29]:
tribonacci_recussive(6)

7

In [28]:
def fibonacci_recursive(n):
    if n <= 1:
        return 0
    elif n == 2:
        return 1
    else:
        return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)

In [25]:
fibonacci_recursive(10)

34

In [39]:
def tribonacci_memo(n, memo=None):
    if n in memo:
        return memo[n]
    else:
        ans1 = tribonacci_memo(n - 1, memo)
        ans2 = tribonacci_memo(n - 2, memo)
        ans3 = tribonacci_memo(n - 3, memo)
        res = ans1 + ans2 + ans3
        memo[n] = res
        return res


In [40]:
memo = {0: 0, 1:0 , 2:1}
tribonacci_memo(7, memo)

13

In [43]:
"""
Longest common sequence in two strings
example BBBABDABAA and AAAABDABBAABB the longest common is ABDAB
1. We use brute force approach
"""
def lcs_brute_force(first, second):
    len_first = len(first)
    len_second = len(second)
    lcs_start, lcs_end = -1, -1
    max_lcs = -1
    for i1 in range(len_first):
        for j1 in range(i1, len_first):
            for i2 in range(len_second):
                for j2 in range(i2, len_second):
                    slice_first = slice(i1, j1)
                    slice_second = slice(i2, j2)
                    if first[slice_first] == second[slice_second] and j1 -i1 > max_lcs:
                        max_lcs = j1 - i1
                        lcs_start = i1
                        lcs_end = j1
    print("LCS: ", first[lcs_start: lcs_end])
    return max_lcs

In [44]:
a = "BBBABDABAA"
b = "AAAABDABBAABB"
lcs_brute_force(a, b)

LCS:  ABDAB


5

In [45]:
"""
2. Using tabular method
"""
import numpy as np
def lcs_tabular(first, second):
    table = np.zeros((len(first), len(second)), dtype=int)
    for i in range(len(first)):
        for j in range(len(second)):
            if first[i] == second[j]:
                table[i, j] += 1 + table[i - 1][j - 1]
    print(table)
    return np.max(table)

In [46]:
a = "BBBABDABAA"
b = "AAAABDABBAABB"
lcs_tabular(a, b)

[[0 0 0 0 1 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 0 0 1 2 0 0 1 2]
 [0 0 0 0 1 0 0 1 2 0 0 1 2]
 [3 1 1 1 0 0 1 0 0 3 1 0 0]
 [0 0 0 0 2 0 0 2 1 0 0 2 1]
 [0 0 0 0 0 3 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 4 0 0 1 1 0 0]
 [0 0 0 0 2 0 0 5 1 0 0 2 1]
 [2 1 1 1 0 0 1 0 0 2 1 0 0]
 [1 3 2 2 0 0 1 0 0 1 3 0 0]]


np.int64(5)