In [1]:
import numpy as np
from scipy import linalg

In [2]:
n_states: int = 3
P = np.zeros((n_states, n_states), np.float32)
P[0, 1] = 0.7
P[0, 2] = 0.3
P[1, 0] = 0.5
P[1, 2] = 0.5
P[2, 1] = 0.1
P[2, 2] = 0.9
print(P)

[[0.  0.7 0.3]
 [0.5 0.  0.5]
 [0.  0.1 0.9]]


In [9]:
assert ((np.sum(P, axis=1) == 1).all())

In [10]:
R = np.zeros((n_states, n_states), np.float32)
R[0,1] = 1
R[0,2] = 10
R[1,0] = 0
R[1,2] = 1
R[2,1] = -1
R[2,2] = 10
R_expected = np.sum(P * R, axis=1, keepdims=True)
print(R_expected)

[[3.7]
 [0.5]
 [8.9]]


In [11]:
"""
Now Bellman Equation
Ax = b where A = (1 - gamma)P and b = R
"""
gamma = 0.9
A = np.eye(n_states) - gamma * P
B = R_expected
V = linalg.solve(A, B)
print(V)

[[65.54069695]
 [64.90787279]
 [77.58791305]]


In [12]:
"""
MDP (SARP𝜞)
where S is set of states
      A is set of actions
      R is reward function
      P is transition probability function
      gamma is discount factor associated with future rewards
"""
# Example
n_states = 6
P_pi = np.zeros((n_states, n_states), np.float32)
R = np.zeros_like(P_pi)
P_pi[0, 1] = 0.5
P_pi[0, 3] = 0.5
P_pi[1, 2] = 0.5
P_pi[1, 5] = 0.5
P_pi[2, 4] = 0.5
P_pi[2, 5] = 0.5
P_pi[4, 5] = 0.5
P_pi[4, 0] = 0.5
P_pi[3, 0] = 0.5
P_pi[3, 3] = 0.5
P_pi[5, 5] = 1
print(P_pi)

[[0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.5 0.  0.  0.5]
 [0.  0.  0.  0.  0.5 0.5]
 [0.5 0.  0.  0.5 0.  0. ]
 [0.5 0.  0.  0.  0.  0.5]
 [0.  0.  0.  0.  0.  1. ]]


In [13]:
# Reward Matrix
R[0, 1] = -2
R[0, 3] = -1
R[1, 2] = -2
R[1, 5] = 0
R[2, 4] = 15
R[2, 5] = 10
R[4, 5] = 10
R[4, 0] = -10
R[3, 3] = -1
R[3, 0] = -3
print(R)

[[  0.  -2.   0.  -1.   0.   0.]
 [  0.   0.  -2.   0.   0.   0.]
 [  0.   0.   0.   0.  15.  10.]
 [ -3.   0.   0.  -1.   0.   0.]
 [-10.   0.   0.   0.   0.  10.]
 [  0.   0.   0.   0.   0.   0.]]


In [14]:
assert((np.sum(P_pi, axis=1) == 1).all())

In [15]:
R_expected = np.sum(P_pi * R, axis=1, keepdims=True)
R_expected

array([[-1.5],
       [-1. ],
       [12.5],
       [-2. ],
       [ 0. ],
       [ 0. ]], dtype=float32)

In [16]:
# Now Bellman Equation
gamma = 0.9
A = np.eye(n_states, n_states) - gamma * P_pi
B = R_expected
V = linalg.solve(A, B)
V

array([[-1.78587054],
       [ 4.46226241],
       [12.13836124],
       [-5.09753029],
       [-0.80364172],
       [ 0.        ]])

In [17]:
gamma = 0
A = np.eye(n_states, n_states) - gamma * P_pi
B = R_expected
V = linalg.solve(A, B)
V

array([[-1.5],
       [-1. ],
       [12.5],
       [-2. ],
       [ 0. ],
       [ 0. ]])

In [23]:
R_sa = np.zeros((n_states*2, 1))
R_sa[0] = -2 # study in state 0
R_sa[1] = -1 # social in state 0
R_sa[2] = -2 # study in state 1
R_sa[3] = 0 # sleep in state 1
R_sa[4] = 10 # sleep in state 2
R_sa[5] = +15 # beer in state 2
R_sa[6] = -1 # social in state 3 (social)
R_sa[7] = -3 # study in state 3 (social)
R_sa[8] = 10 # sleep in state 4 (pub)
R_sa[9] = -10 # study in state 4 (pub)
R_sa.shape

(12, 1)

In [24]:
R

array([[  0.,  -2.,   0.,  -1.,   0.,   0.],
       [  0.,   0.,  -2.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  15.,  10.],
       [ -3.,   0.,   0.,  -1.,   0.,   0.],
       [-10.,   0.,   0.,   0.,   0.,  10.],
       [  0.,   0.,   0.,   0.,   0.,   0.]], dtype=float32)

In [25]:
"""
States present Social, Class1, Class2, Class3, Pub and Bed
"""

'\nStates present Social, Class1, Class2, Class3, Pub and Bed\n'

In [32]:
import numpy as np
import scipy.optimize
n_states = 3
n_actions = 2
mu = np.array([[1,0,0]]).T
mu

array([[1],
       [0],
       [0]])

In [33]:
R_A = np.zeros((n_states,1), np.float32)
R_A[0,0] = 1
R_A[1,0] = 0
R_A[2,0] = 0
R_A

array([[1.],
       [0.],
       [0.]], dtype=float32)

In [34]:
P_A = np.zeros((n_states, n_states), np.float32)
P_A[0,1] = 1
P_A[1,0] = 1
P_A[2,1] = 1
P_A

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [35]:
gamma = 0.9
A_up_A = gamma * P_A - np.eye(3,3)
A_up_A

array([[-1.        ,  0.89999998,  0.        ],
       [ 0.89999998, -1.        ,  0.        ],
       [ 0.        ,  0.89999998, -1.        ]])

In [36]:
R_B = np.zeros((n_states,1), np.float32)
R_B[0,0] = 10
R_B[1,0] = 1
R_B[2,0] = 10
# Define transition matrix
P_B = np.zeros((n_states, n_states), np.float32)
P_B[0,2] = 1
P_B[1,2] = 1
P_B[2,2] = 1
# Upper bound A matrix for action B
A_up_B = gamma * P_B - np.eye(3,3)
A_up_B

array([[-1.        ,  0.        ,  0.89999998],
       [ 0.        , -1.        ,  0.89999998],
       [ 0.        ,  0.        , -0.10000002]])

In [38]:
# Upper Bound for all actions and all states
A_up = np.vstack((A_up_A, A_up_B))
"""
Verify the shape: number of constraints are equal to |actions| * |states|
"""
assert(A_up.shape[0] == n_states * n_actions)
# Reward vector is obtained by stacking the two vectors
R = np.vstack((R_A, R_B))
R

array([[ 1.],
       [ 0.],
       [ 0.],
       [10.],
       [ 1.],
       [10.]], dtype=float32)

In [39]:
c = mu
b_up = -R
res = scipy.optimize.linprog(c, A_ub=A_up, b_ub=b_up)
V_ = res.x
V_

array([99.99997616, 90.99997616, 99.99997616])

In [40]:
V = V_.reshape((-1,1))
V

array([[99.99997616],
       [90.99997616],
       [99.99997616]])